In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [2]:
area=[2600,3000,3200,3600,4000]
price=[550000,565000,610000,680000,725000]
df=pd.DataFrame(columns=['area','price'])
df['area']=pd.Series(area)
df['price']=pd.Series(price)

In [3]:
model=linear_model.LinearRegression()

In [21]:
model.fit(df[['area']],df.price)

LinearRegression()

In [22]:
model.coef_

array([135.78767123])

In [23]:
model.intercept_

180616.43835616432

In [24]:
model.predict([[3100]])

c:\users\shivam\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([601558.21917808])

In [25]:
import pickle

In [28]:

with open ("linear_regress.pickle" ,'wb') as file:
    pickle.dump(model,file)

In [29]:
model.predict([[3322]])

c:\users\shivam\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([631703.08219178])

In [33]:
import joblib

In [34]:
joblib.dump(model,'model_joblib')

['model_joblib']